/* AEGIS_SCENARIOS — six scripted attack campaigns for the demo.
 * Timelines are 8-14 events over ~20s. Each event flows through the same
 * pipeline the real platform uses: makeFinding -> adjustScore -> dedupe
 * -> (correlate) -> playbook. viz.target is one of the 3D scene nodes:
 * web | api | db | auth | mail | edge. */
window.AEGIS_SCENARIOS = [
  {
    id: "typosquat-wave",
    title: "Typosquat Wave",
    threat: "A wave of lookalike domains impersonating your brand.",
    description:
      "Someone registers misspellings of your domain and stands up fake login pages. " +
      "Watch four engines notice different pieces of the same campaign \u2014 and the correlator stitch them into one case.",
    timeline: [
      { t: 0, engine: "typo_watch", title: "3 lookalike domains live for harborline-bank.com", score: 78,
        entities: { domain: "harborline-bank.com", lookalikes: ["harborIine-bank.com", "harborlinebank-secure.com", "harbor-linebank.com"] },
        evidence: { techniques: ["homoglyph", "omission", "compound"] },
        viz: { target: "web", kind: "probe" } },
      { t: 1800, engine: "url_intel", title: "Shortened link resolves to lookalike login page", score: 84,
        entities: { url: "https://hbr.ly/x91k", final: "harborlinebank-secure.com/login" },
        evidence: { hops: 3, domain_age_days: 2 },
        viz: { target: "mail", kind: "probe" } },
      { t: 3600, engine: "phish_kit", title: "Phishing kit detected: HarborPhish v3 at harborlinebank-secure.com", score: 91,
        entities: { url: "harborlinebank-secure.com", kit: "HarborPhish v3" },
        evidence: { c2: ["panel.hb-stats.net"], harvests: ["username", "password", "mfa_token"] },
        viz: { target: "web", kind: "probe" } },
      { t: 5400, engine: "dns_sentinel", title: "Lookalike MX records point to attacker mail server", score: 72,
        entities: { zone: "harborlinebank-secure.com", rtype: "MX" },
        evidence: { after: ["mx.attacker-relay.net"] },
        viz: { target: "mail", kind: "probe" } },
      { t: 7200, engine: "typo_watch", title: "2 more lookalikes live (transposition variants)", score: 76,
        entities: { domain: "harborline-bank.com", lookalikes: ["harborlien-bank.com", "haborline-bank.com"] },
        evidence: { techniques: ["transposition", "omission"] },
        viz: { target: "web", kind: "probe" } },
      { t: 9000, engine: "url_intel", title: "QR code in email campaign decodes to lookalike URL", score: 69,
        entities: { final: "harborIine-bank.com/verify" },
        evidence: { hops: 2, domain_age_days: 1 },
        viz: { target: "mail", kind: "probe" } },
      { t: 10800, engine: "phish_kit", title: "Harvest form posting credentials to external host", score: 94,
        entities: { url: "harborlinebank-secure.com", kit: "HarborPhish v3" },
        evidence: { posts_to: "panel.hb-stats.net/collect" },
        viz: { target: "web", kind: "breach" } },
      { t: 13000, engine: "auth_watch", title: "Login attempts using phished-credential replay", score: 88,
        entities: { user: "4 accounts", src: "185.220.101.4" },
        evidence: { failures: 0, successes: 4 },
        viz: { target: "auth", kind: "breach" } },
      { t: 15500, engine: "anomaly_mind", title: "Impossible travel: 4 users (Portsmouth \u2192 Lagos, 11 min)", score: 81,
        entities: { user: "4 accounts" },
        evidence: { route: "Portsmouth,US->Lagos,NG", minutes_apart: 11 },
        viz: { target: "auth", kind: "breach" } },
      { t: 18000, engine: "canary_trip", title: "Canary AWS key pasted into lookalike form tripped", score: 96,
        entities: { canary: "canary-aws-key-04", src: "185.220.101.4" },
        evidence: { hit_count: 1 },
        viz: { target: "edge", kind: "exfil" } },
    ],
    playbook: {
      name: "Brand impersonation takedown",
      steps: [
        "File registrar takedown requests for all 5 lookalike domains",
        "Push the domains + C2 host to the mail-gateway and DNS-filter blocklists",
        "Force password resets on the 4 affected accounts",
        "Revoke all sessions; rotate the tripped canary credentials",
        "Open abuse cases with the registrars and preserve evidence",
      ],
    },
  },
  {
    id: "credential-stuffing",
    title: "Credential Stuffing",
    threat: "Stolen passwords from other breaches, tried against your logins.",
    description:
      "Billions of leaked credentials circulate online. Attackers try them against your login page automatically. " +
      "auth_watch recognizes the shape of the attack; anomaly_mind spots the logins that succeed.",
    timeline: [
      { t: 0, engine: "auth_watch", title: "412 failed logins in 60s on /login", score: 74,
        entities: { src: "91.108.44.12", failures: 412 },
        evidence: { window_minutes: 1 },
        viz: { target: "auth", kind: "probe" } },
      { t: 1500, engine: "anomaly_mind", title: "Login velocity 40\u00d7 baseline", score: 71,
        entities: { user: "aggregate" },
        evidence: { z: 6.4 },
        viz: { target: "auth", kind: "probe" } },
      { t: 3200, engine: "auth_watch", title: "Password spray: 1 password tried against 300 accounts", score: 86,
        entities: { src: "91.108.44.12", users: 300 },
        evidence: { window_minutes: 10, failures: 284 },
        viz: { target: "auth", kind: "probe" } },
      { t: 5000, engine: "port_watch", title: "Attacker IP scanning alternate auth ports", score: 48,
        entities: { host: "auth-01", ports: [8443, 9443] },
        evidence: { baseline: [443] },
        viz: { target: "edge", kind: "probe" } },
      { t: 6800, engine: "auth_watch", title: "38 successful logins from sprayed accounts", score: 93,
        entities: { user: "38 accounts", src: "91.108.44.12" },
        evidence: { successes: 38 },
        viz: { target: "auth", kind: "breach" } },
      { t: 8600, engine: "anomaly_mind", title: "Sessions from new ASN + new device fingerprints", score: 79,
        entities: { user: "38 accounts" },
        evidence: { z: 5.1 },
        viz: { target: "auth", kind: "breach" } },
      { t: 10500, engine: "canary_trip", title: "Honeypot admin account 'svc-backup' logged into", score: 95,
        entities: { canary: "svc-backup", src: "91.108.44.12" },
        evidence: { hit_count: 1 },
        viz: { target: "auth", kind: "breach" } },
      { t: 12400, engine: "url_intel", title: "Attacker IP posted in credential-dump forum thread", score: 62,
        entities: { src: "91.108.44.12" },
        evidence: { hops: 0, domain_age_days: 900 },
        viz: { target: "edge", kind: "probe" } },
      { t: 14500, engine: "auth_watch", title: "MFA fatigue: 12 push prompts to one user in 3 min", score: 89,
        entities: { user: "m.okafor", src: "91.108.44.12" },
        evidence: { prompts: 12, window_minutes: 3 },
        viz: { target: "auth", kind: "breach" } },
      { t: 17000, engine: "anomaly_mind", title: "Mailbox rules created to hide password-reset mail", score: 90,
        entities: { user: "m.okafor" },
        evidence: { z: 4.8 },
        viz: { target: "mail", kind: "exfil" } },
    ],
    playbook: {
      name: "Credential stuffing containment",
      steps: [
        "Rate-limit and block the attacking IP ranges at the edge",
        "Lock the 38 compromised accounts",
        "Force MFA re-enrollment for all sprayed users (number-matching)",
        "Revoke sessions and delete the hidden mailbox rules",
        "Notify affected users with reset instructions",
      ],
    },
  },
  {
    id: "phishing-kit",
    title: "Phishing Kit",
    threat: "A professional phishing kit targeting your customers.",
    description:
      "Criminals buy ready-made phishing kits the way businesses buy software. phish_kit recognizes the kit's " +
      "fingerprint; url_intel and dns_sentinel watch it spread and shift infrastructure.",
    timeline: [
      { t: 0, engine: "url_intel", title: "Email link unshortens to fresh domain, age 6 hours", score: 81,
        entities: { url: "https://t.co/q8v2mz", final: "secure-harborline.top/verify" },
        evidence: { hops: 4, domain_age_days: 0.25 },
        viz: { target: "mail", kind: "probe" } },
      { t: 1800, engine: "phish_kit", title: "Page DOM matches EvilLogin-style kit fingerprint", score: 90,
        entities: { url: "secure-harborline.top", kit: "EvilLogin v2.4" },
        evidence: { c2: ["c2.evillogin.su"], harvests: ["email", "password", "session_cookie"] },
        viz: { target: "web", kind: "probe" } },
      { t: 3600, engine: "typo_watch", title: "Sender domain is a lookalike of your vendor", score: 77,
        entities: { domain: "vendor-portal.com", lookalikes: ["vender-portal.com"] },
        evidence: { techniques: ["omission"] },
        viz: { target: "mail", kind: "probe" } },
      { t: 5400, engine: "phish_kit", title: "Kit phones home to known C2 panel", score: 94,
        entities: { url: "secure-harborline.top", kit: "EvilLogin v2.4" },
        evidence: { posts_to: "c2.evillogin.su/in" },
        viz: { target: "web", kind: "breach" } },
      { t: 7200, engine: "dns_sentinel", title: "Domain fast-flux: 9 A records in 20 minutes", score: 83,
        entities: { zone: "secure-harborline.top", rtype: "A" },
        evidence: { after: ["9 rotating hosts"] },
        viz: { target: "edge", kind: "probe" } },
      { t: 9000, engine: "secret_sentry", title: "Kit zip with your brand assets found in public repo", score: 66,
        entities: { repo: "github.com/anon/evillogin-custom", kind: "brand assets" },
        evidence: { path: "kits/harborline.zip" },
        viz: { target: "web", kind: "probe" } },
      { t: 11000, engine: "auth_watch", title: "First credential submission captured by kit", score: 92,
        entities: { user: "1 account", src: "c2.evillogin.su" },
        evidence: { successes: 1 },
        viz: { target: "web", kind: "breach" } },
      { t: 13200, engine: "anomaly_mind", title: "Victim session cookie replayed from new IP", score: 88,
        entities: { user: "1 account" },
        evidence: { route: "Portsmouth,US->Bucharest,RO", minutes_apart: 6 },
        viz: { target: "auth", kind: "exfil" } },
      { t: 15500, engine: "canary_trip", title: "Canary email address submitted to kit \u2014 attribution ping", score: 85,
        entities: { canary: "canary-email-02", src: "c2.evillogin.su" },
        evidence: { hit_count: 1 },
        viz: { target: "edge", kind: "probe" } },
      { t: 18000, engine: "url_intel", title: "Kit cloned to a 2nd domain within the hour", score: 87,
        entities: { final: "harborline-verify.top" },
        evidence: { hops: 1, domain_age_days: 0.1 },
        viz: { target: "web", kind: "probe" } },
    ],
    playbook: {
      name: "Phishing kit takedown",
      steps: [
        "Sinkhole and request takedown of both kit domains",
        "Block the C2 panel hosts at the edge firewall",
        "Quarantine the phishing emails mailbox-wide",
        "Reset credentials for submitted accounts; kill their sessions",
        "Feed the kit IOCs into threat intel for future matching",
      ],
    },
  },
  {
    id: "cve-exploit-probe",
    title: "CVE Exploit Probe",
    threat: "A fresh RCE in your VPN gateway \u2014 exploit code is public.",
    description:
      "A critical CVE drops for software you run, and proof-of-concept code follows within days. " +
      "cve_watch matches it to your inventory; the other engines watch the exploit arrive in real time.",
    timeline: [
      { t: 0, engine: "cve_watch", title: "CVE-2026-21407 published: RCE in VPN gateway you run", score: 88,
        entities: { cve: "CVE-2026-21407", product: "vpn-gateway 4.2" },
        evidence: { epss: 0.82, in_kev: false, poc: false },
        viz: { target: "edge", kind: "probe" } },
      { t: 1600, engine: "port_watch", title: "Internet-wide scan hitting your VPN port from 40 hosts", score: 73,
        entities: { host: "vpn-01", ports: [443] },
        evidence: { baseline: [443] },
        viz: { target: "edge", kind: "probe" } },
      { t: 3400, engine: "cve_watch", title: "Public exploit PoC posted \u2014 your version is vulnerable", score: 95,
        entities: { cve: "CVE-2026-21407", product: "vpn-gateway 4.2" },
        evidence: { epss: 0.94, in_kev: true, poc: true },
        viz: { target: "edge", kind: "probe" } },
      { t: 5200, engine: "auth_watch", title: "Auth bypass attempts against VPN login", score: 84,
        entities: { user: "vpn users", src: "multiple" },
        evidence: { failures: 1200 },
        viz: { target: "edge", kind: "probe" } },
      { t: 7000, engine: "anomaly_mind", title: "Unusual process spawn on VPN appliance", score: 91,
        entities: { user: "system:vpn-01" },
        evidence: { z: 7.2 },
        viz: { target: "edge", kind: "breach" } },
      { t: 8800, engine: "port_watch", title: "New outbound connection from VPN to unknown host", score: 89,
        entities: { host: "vpn-01", ports: [4444] },
        evidence: { baseline: [] },
        viz: { target: "edge", kind: "exfil" } },
      { t: 10600, engine: "dns_sentinel", title: "VPN host resolving attacker-controlled domain", score: 86,
        entities: { zone: "vpn-01.internal", rtype: "A" },
        evidence: { after: ["stage.c2-relay.net"] },
        viz: { target: "edge", kind: "breach" } },
      { t: 12500, engine: "canary_trip", title: "Canary file on VPN share accessed", score: 97,
        entities: { canary: "canary-doc-finance", src: "vpn-01" },
        evidence: { hit_count: 3 },
        viz: { target: "edge", kind: "breach" } },
      { t: 14800, engine: "anomaly_mind", title: "Lateral movement: VPN \u2192 internal file server", score: 93,
        entities: { user: "system:vpn-01" },
        evidence: { z: 6.9 },
        viz: { target: "db", kind: "breach" } },
      { t: 17200, engine: "secret_sentry", title: "Service creds from VPN found in memory dump", score: 90,
        entities: { repo: "vpn-01:/proc/mem", kind: "service credentials" },
        evidence: { path: "/proc/kcore" },
        viz: { target: "db", kind: "exfil" } },
    ],
    playbook: {
      name: "VPN compromise response",
      steps: [
        "Isolate the VPN appliance from the network immediately",
        "Block the C2 host; rotate all service credentials",
        "Patch to the fixed version and verify with a rescan",
        "Hunt for lateral movement across the estate",
        "Restore from a known-good snapshot if root compromise is confirmed",
      ],
    },
  },
  {
    id: "cloud-misconfig-drift",
    title: "Cloud Misconfig Drift",
    threat: "A quiet config change opens your cloud to the internet.",
    description:
      "No malware, no phishing \u2014 just drift. A bucket goes public, a security group opens, an admin role appears. " +
      "cloud_posture diffs live state against what you declared; the rest is what attackers do with the opening.",
    timeline: [
      { t: 0, engine: "cloud_posture", title: "S3 bucket 'backups' flipped to public-read", score: 92,
        entities: { bucket: "backups" },
        evidence: { policy: "Principal: *" },
        viz: { target: "db", kind: "probe" } },
      { t: 1800, engine: "cloud_posture", title: "Security group allows 0.0.0.0/0 on port 22", score: 78,
        entities: { port: 22 },
        evidence: {},
        viz: { target: "edge", kind: "probe" } },
      { t: 3600, engine: "port_watch", title: "SSH brute force begins on the exposed instance", score: 74,
        entities: { host: "i-0a91f2", ports: [22] },
        evidence: { baseline: [] },
        viz: { target: "edge", kind: "probe" } },
      { t: 5400, engine: "auth_watch", title: "SSH login success from unknown key", score: 94,
        entities: { user: "ubuntu", src: "103.99.0.77" },
        evidence: { failures: 900, successes: 1 },
        viz: { target: "edge", kind: "breach" } },
      { t: 7200, engine: "cloud_posture", title: "IAM policy drift: new admin role created", score: 90,
        entities: { role: "TempAdmin-Restore" },
        evidence: { creator: "compromised-key" },
        viz: { target: "api", kind: "breach" } },
      { t: 9000, engine: "anomaly_mind", title: "CloudTrail logging disabled in the region", score: 96,
        entities: { user: "system" },
        evidence: { z: 8.1 },
        viz: { target: "api", kind: "breach" } },
      { t: 11000, engine: "secret_sentry", title: "AWS keys found in instance user-data script", score: 88,
        entities: { repo: "i-0a91f2 user-data", kind: "AWS access key" },
        evidence: { path: "/user-data" },
        viz: { target: "api", kind: "breach" } },
      { t: 13000, engine: "anomaly_mind", title: "Cryptominer process signature on the instance", score: 82,
        entities: { user: "system:i-0a91f2" },
        evidence: { z: 5.7 },
        viz: { target: "api", kind: "breach" } },
      { t: 15200, engine: "cloud_posture", title: "Snapshot of prod DB shared publicly", score: 98,
        entities: { bucket: "prod-db-snapshot" },
        evidence: { policy: "shared with allUsers" },
        viz: { target: "db", kind: "exfil" } },
      { t: 17500, engine: "canary_trip", title: "Canary S3 object accessed by external IP", score: 93,
        entities: { canary: "canary-s3-object", src: "103.99.0.77" },
        evidence: { hit_count: 2 },
        viz: { target: "db", kind: "exfil" } },
    ],
    playbook: {
      name: "Cloud compromise rollback",
      steps: [
        "Revoke the public bucket policy and the public snapshot share",
        "Delete the rogue IAM role; re-enable CloudTrail",
        "Terminate the compromised instance",
        "Rotate every key the instance could see",
        "Diff IaC against live state to find the drift source",
      ],
    },
  },
  {
    id: "secret-leak",
    title: "Secret Leak",
    threat: "An API key pushed to a public repo \u2014 bots find it in minutes.",
    description:
      "A developer pushes a commit with a live key. secret_sentry catches it; then you watch, in fast-forward, " +
      "what automated harvesters do with a leaked key when nobody revokes it.",
    timeline: [
      { t: 0, engine: "secret_sentry", title: "Live API key in public GitHub commit", score: 97,
        entities: { repo: "acme/webapp", kind: "API key" },
        evidence: { path: "config/prod.env" },
        viz: { target: "api", kind: "probe" } },
      { t: 1500, engine: "secret_sentry", title: "AWS key pair in the same repo's history", score: 95,
        entities: { repo: "acme/webapp", kind: "AWS access key" },
        evidence: { path: "deploy/old-keys.txt" },
        viz: { target: "api", kind: "probe" } },
      { t: 3200, engine: "url_intel", title: "Key already indexed by secret-scanning bots (2 min after push)", score: 90,
        entities: { final: "scanner-index.example" },
        evidence: { hops: 1, domain_age_days: 400 },
        viz: { target: "edge", kind: "probe" } },
      { t: 5000, engine: "cloud_posture", title: "The leaked AWS key just called sts:GetCallerIdentity", score: 98,
        entities: { role: "leaked-key" },
        evidence: { creator: "185.220.101.4" },
        viz: { target: "edge", kind: "breach" } },
      { t: 6800, engine: "anomaly_mind", title: "New EC2 instances spinning up in 3 regions", score: 94,
        entities: { user: "system" },
        evidence: { z: 7.8 },
        viz: { target: "api", kind: "breach" } },
      { t: 8600, engine: "auth_watch", title: "Console login with leaked key from new IP", score: 93,
        entities: { user: "root", src: "185.220.101.4" },
        evidence: { successes: 1 },
        viz: { target: "api", kind: "breach" } },
      { t: 10500, engine: "canary_trip", title: "Canary token embedded near the key also fired", score: 89,
        entities: { canary: "canary-in-repo", src: "185.220.101.4" },
        evidence: { hit_count: 1 },
        viz: { target: "api", kind: "probe" } },
      { t: 12400, engine: "port_watch", title: "Attacker scanning outward from your compromised instance", score: 81,
        entities: { host: "i-0b77c1", ports: [22, 445, 3389] },
        evidence: { baseline: [443] },
        viz: { target: "edge", kind: "probe" } },
      { t: 14500, engine: "dns_sentinel", title: "Instance resolving mining-pool domains", score: 84,
        entities: { zone: "i-0b77c1.internal", rtype: "A" },
        evidence: { after: ["pool.mining-relay.net"] },
        viz: { target: "api", kind: "exfil" } },
      { t: 16800, engine: "secret_sentry", title: "Second key found: CI env file in another repo", score: 91,
        entities: { repo: "acme/mobile", kind: "CI secret" },
        evidence: { path: ".ci/env" },
        viz: { target: "api", kind: "probe" } },
    ],
    playbook: {
      name: "Leaked credential response",
      steps: [
        "Revoke both keys immediately at the provider",
        "Purge the secrets from git history (rotate anything that can't be purged)",
        "Terminate attacker-spun instances",
        "Audit CloudTrail for everything the key touched",
        "Move secrets to a vault and add a pre-commit hook",
      ],
    },
  },
];
